version: "3"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: appDB2
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d:ro
      - db_volume:/var/lib/mysql
    ports:
      - "3308:3306"
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/content:/etc/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    links:
      - db
  apache:
    build: ./apache
    restart: always
    volumes:
      - ./apache/content:/var/www/html/
      - ./apache/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8081:80"
    links:
      - db
      - nginx
      - redis
    depends_on:
    - db
  redis:
    image: redis:alpine3.16
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf

volumes:
  db_volume:
